// src/app/layout.js
import './globals.css';
import { ThemeProvider } from 'next-themes';
import ClientClerkProvider from '../components/ClientClerkProvider'; // adjust path if needed

export const metadata = {
  title: 'My Phone App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        style={{
          fontFamily:
            'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
        }}
      >
        <ClientClerkProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </ClientClerkProvider>
      </body>
    </html>
  );
}


// // src/app/layout.js
// import './globals.css';
// import { ThemeProvider } from 'next-themes';
// import { ClerkProvider } from '@clerk/nextjs';

// export const metadata = {
//   title: 'My Phone App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({ children }) {
//   return (
//     <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
//       <html lang="en" style={{ fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif' }} suppressHydrationWarning>
//         <head />
//         <body>
//           <ThemeProvider
//             attribute="class"
//             defaultTheme="system"
//             enableSystem
//             disableTransitionOnChange
//           >
//             {children}
//           </ThemeProvider>
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }




// // src/app/layout.js
// import './globals.css';
// import { ThemeProvider } from 'next-themes';
// import { ClerkProvider } from '@clerk/nextjs';
// import { Inter } from 'next/font/google';

// // --- Google Font (Inter) ---
// const geistSans = Inter({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// export const metadata = {
//   title: 'My Phone App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({ children }) {
//   return (
//      <ClerkProvider
//       publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
//     >
//       <html
//         lang="en"
//         className={geistSans.variable}
//         suppressHydrationWarning
//       >
//         <head />
//         <body>
//           <ThemeProvider
//             attribute="class"
//             defaultTheme="system"
//             enableSystem
//             disableTransitionOnChange
//           >
//             {children}
//           </ThemeProvider>
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }







// // import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { ThemeProvider } from "next-themes";
// import { ClerkProvider } from '@clerk/nextjs';
// import { Inter, Roboto_Mono } from "next/font/google";

// const geistSans = Inter({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Roboto_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });


// export const metadata = {
//   title: "My Phone App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <ClerkProvider>
//       <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning>
//         <head />
//         <body>
//           <ThemeProvider
//             attribute="class"
//             defaultTheme="system"
//             enableSystem
//             disableTransitionOnChange
//           >
//             {children}
//           </ThemeProvider>
//         </body>
//       </html>
//     </ClerkProvider>
//   );

// }
